### PR TITLE
Add default environment variables for without docker-compose

### PR DESCRIPTION
**Pull request by divinespear**
It checks environment variables first. when It does not exists and linked postgres container detected, set missing environment variable to container's value.

### CODE REVIEW

**Comment by benhutchins** [comment]
I do not believe either `POSTGRES_PORT_5432_TCP_ADDR` and `POSTGRES_ENV_POSTGRES_PASSWORD` will be populated with moving to newer versions of the `docker-compose.yml` file.

**Comment by divinespear** [comment]
Sure It's meaningless for docker-compose users cause all db envs already set. this pr is for otherwise case users. (In my case, I use only one postgres container and all other containers shares it.)

**Comment by benhutchins** [comment]
Well, not meaningless. Even you can continue to use `docker-compose`, you can specify a running container rather than having `docker-compose` bring up another postgres container.

However, the entire `--link` argument is deprecated and will potentially be removed. So you won't have access to the password like this using `docker` for long, see here: https://docs.docker.com/engine/userguide/networking/default_network/dockerlinks/

I would also imagine most people not using `docker-compose` are more likely using a hosted database, on something like Amazon RDS. So the amount of users this would be useful for is low, which is why I originally removed the default values for these environment variables.

What I generally do, when not using `docker-compose`, is create a set of simple bash scripts or a `Makefile` to help start and stop containers, which can pass over the environment variables I need. This way I'm not writing long `docker run` commands that I might need to rerun. You can also use the [`--env-file` option](https://docs.docker.com/engine/reference/commandline/run/#/set-environment-variables--e---env---env-file). This would likely be the best option for you.

As for this PR, since it's going in the wrong direction, I'm going to close it. I don't want to encourage use of deprecated features in Docker. If you'd like to have that, you can always create your own image, create a `Dockerfile` like this:

```
FROM benhutchins/taiga

ADD my-own-entrypoint.sh /docker-entrypoint.sh

# or instead of using ADD, specify defaults using the ENV command

ENV TAIGA_DB_HOST db
ENV TAIGA_DB_NAME postgres
ENV TAIGA_DB_USER postgres
END TAIGA_DB_PASSWORD password
```

**Comment by divinespear** [comment]
Thanks for mention that reference. I never noticed (or focus to read) that.

**Comment by benhutchins** [comment]
Thanks for the pull request @divinespear, and offering to make this project better. I feel free to contribute again in the future.

**Pull request closed without merging**
